// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type ClientFingerprint struct {
	ID           int64  `json:"id"`
	ClientID     int64  `json:"client_id"`
	UserAgent    string `json:"user_agent"`
	ScreenWidth  int64  `json:"screen_width"`
	ScreenHeight int64  `json:"screen_height"`
	Fpversion    int32  `json:"fpversion"`
	Fphash       string `json:"fphash"`
	CreatedAt    int64  `json:"created_at"`
}

type ClientIdentifier struct {
	ID        int64  `json:"id"`
	Ident     string `json:"ident"`
	CreatedAt int64  `json:"created_at"`
}

type Like struct {
	ID     int64 `json:"id"`
	TsNano int64 `json:"ts_nano"`
	UrlID  int64 `json:"url_id"`
}

type LikeCount struct {
	ID    int64 `json:"id"`
	UrlID int64 `json:"url_id"`
	Count int64 `json:"count"`
}

type Url struct {
	ID     int64  `json:"id"`
	Url    string `json:"url"`
	TsNano int64  `json:"ts_nano"`
}

type View struct {
	ID     int64 `json:"id"`
	TsNano int64 `json:"ts_nano"`
	UrlID  int64 `json:"url_id"`
}

type ViewCount struct {
	ID    int64 `json:"id"`
	UrlID int64 `json:"url_id"`
	Count int64 `json:"count"`
}
