// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type ClientFingerprint struct {
	ID            int64  `json:"id"`
	ClientID      int64  `json:"client_id"`
	UserAgent     string `json:"user_agent"`
	UserAgentData string `json:"user_agent_data"`
	ScreenWidth   int64  `json:"screen_width"`
	ScreenHeight  int64  `json:"screen_height"`
	Fpversion     int32  `json:"fpversion"`
	Fphash        string `json:"fphash"`
	CreatedAt     int64  `json:"created_at"`
}

type ClientIdentifier struct {
	ID        int64  `json:"id"`
	Token     string `json:"token"`
	CreatedAt int64  `json:"created_at"`
}

type Like struct {
	ID        int64 `json:"id"`
	UrlID     int64 `json:"url_id"`
	ClientID  int64 `json:"client_id"`
	CreatedAt int64 `json:"created_at"`
}

type LikeCount struct {
	ID        int64 `json:"id"`
	UrlID     int64 `json:"url_id"`
	Count     int64 `json:"count"`
	UpdatedAt int64 `json:"updated_at"`
}

type RandflakeLease struct {
	Uuid      []byte `json:"uuid"`
	NodeID    int64  `json:"node_id"`
	CreatedAt int64  `json:"created_at"`
	ExpiresAt int64  `json:"expires_at"`
}

type Url struct {
	ID        int64  `json:"id"`
	Url       string `json:"url"`
	CreatedAt int64  `json:"created_at"`
}

type View struct {
	ID        int64 `json:"id"`
	UrlID     int64 `json:"url_id"`
	ClientID  int64 `json:"client_id"`
	CreatedAt int64 `json:"created_at"`
}

type ViewCount struct {
	ID        int64 `json:"id"`
	UrlID     int64 `json:"url_id"`
	Count     int64 `json:"count"`
	UpdatedAt int64 `json:"updated_at"`
}
